apiVersion: v1
kind: ConfigMap
metadata:
  name: ansible-playbooks
data:
  k3s-ansible-playbook.yml: |
    ---
    - name: Manage k3s cluster
      hosts: localhost
      tasks:
        - name: List all pods in the default namespace
          kubernetes.core.k8s_info:
            kind: Pod
            namespace: default
          register: pod_list

        - name: Print pod list
          debug:
            var: pod_list.resources
